---
title: "Predicting seasonal influenza hospitalizations using an ensemble super learner: a simulation study"
---

```{r, include = FALSE}
library(officer)
sfp <- fp_text(
  font.family = "Times New Roman",
  vertical.align = "superscript"
)
```

Jason R. Gantenberg, Kevin W. McConeghy, Chanelle J. Howe, Jon Steingrimsson, Robertus van Aalst, Ayman Chit, Andrew R. Zullo

# Acknowledgments

## Author affiliations
Department of Epidemiology, Brown University School of Public Health, Providence, Rhode Island (Jason R. Gantenberg, Andrew R. Zullo); Department of Health Services, Policy and Practice, Providence, Rhode Island (Jason R. Gantenberg, Kevin M. McConeghy, Andrew R. Zullo); Providence VA Medical Center, Providence, Rhode Island (Kevin M. McConeghy, Andrew R. Zullo); Center for Epidemiologic Research, Brown University School of Public Health, Providence, Rhode Island (Chanelle J. Howe); Department of Biostatistics, Brown University School of Public Health, Providence, Rhode Island (Jon Steingrimsson); Sanofi Pasteur, Swiftwater, Pennsylvania (Robertus van Aalst, Ayman Chit); Department of Health Sciences, University Medical Center Groningen, University of Groningen, Groningen, the Netherlands (Robertus van Aalst); Leslie Dan Faculty of Pharmacy, University of Toronto, Ontario, Canada (Ayman Chit)

## Funding information
This Brown University collaborative research was funded by Sanofi Pasteur (PI: ARZ). ARZ was also supported, in part, by grants R21AG061632 and R01AG065722 from the National Institute on Aging and U54GM115677 from the National Institute of General Medical Sciences. In addition, ARZ was supported by a US Department of Veterans Affairs Office of Academic Affiliations Advanced Fellowship in Health Services Research and Development.

## Conflicts of interest
KWM receives funding support from Seqirus pharmaceuticals and conducts investigator-initiated work for Pfizer.
  
## Data-availability statement
The code necessary to reproduce these results and the output from the super learner procedures are provided in a repository at Open Science Framework **(doi: XXXXXXXXX)**. These materials are also housed permanently at the Brown Digital Repository **(doi/url: XXXXXXXXXXX)**, and the package can be installed directly via the Github repository ([https://www.github.com/jrgant/FluHospPrediction](https://www.github.com/jrgant/FluHospPrediction)).


## Corresponding author
\noindent
Jason R. Gantenberg \
Department of Epidemiology \
Department of Health Services, Policy and Practice \
Brown University School of Public Health \
Providence, RI 02912 \
E-mail: jrgant@brown.edu

# Contributions
JRG helped to refine the study aims, formulated the analysis plan, implemented all coding and analyses, and drafted the initial version of the manuscript. KWM and CJH assisted in formulating the study goals and analysis plan and interpreting the results, in addition to critically revising the manuscript. JS reviewed and contributed to refining the statistical analysis, helped to interpret the results, and critically revised the manuscript. RvA and AC conceived of the project aims, assisted in interpreting the results, and critically revised the manuscript. ARZ helped to conceive of the project aims, formulate the study plan, and interpret the results, in addition to critically revising the manuscript. ARZ and KWM both supervised the project. All authors agreed to the submission of the final version.

## Appreciation
We would like to thank Ashley Naimi, Laura Balzer, and Nicholas Reich for their helpful comments concerning the study aims and the super learner approach, as well as Edward Thommes for his comments on a draft of the manuscript. The super learner algorithm was fit using computational resources and services provided by the Center for Computation and Visualization at Brown University.

## Disclaimer
The views expressed in this article are those of the authors and do not necessarily reflect the position or policy of the Department of Veterans Affairs or the United States Government.

## Prior presentation
An abstract based on portions of the data described in this manuscript was accepted as a poster presentation at the 2021 Annual Meeting of the Society for Epidemiologic Research.

# Keywords

influenza, hospitalization, machine learning, forecasting, public health surveillance, epidemiologic methods

# Abbreviations

ILI, influenza-like illness; EIP, Emerging Infections Program
